"""
Django settings for hours project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from YamJam import yamjam


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# for yamjam working properly on server
cur_user = os.getenv('USER')

ROOT_DIR = os.path.expanduser('~/')

if '10khourslru' in cur_user:
    ROOT_DIR = os.path.dirname(os.path.dirname(ROOT_DIR))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = yamjam(os.path.join(ROOT_DIR, '.yamjam/config.yaml'))['hours']['DJANGO_SECRET_KEY']
GOOGLE_OAUTH2_CLIENT_ID = yamjam(os.path.join(ROOT_DIR, '.yamjam/config.yaml'))['hours']['GOOGLE_CLIENT_ID']
GOOGLE_OAUTH2_CLIENT_SECRET = yamjam(os.path.join(ROOT_DIR, '.yamjam/config.yaml'))['hours']['GOOGLE_CLIENT_SECRET']

# SMPT settings
EMAIL_HOST = 'smtp.beget.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = yamjam(os.path.join(ROOT_DIR, '.yamjam/config.yaml'))['hours']['user']
EMAIL_HOST_PASSWORD = yamjam(os.path.join(ROOT_DIR, '.yamjam/config.yaml'))['hours']['password']
EMAIL_USE_TLS = True


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # TODO load static then debug=False

LOCAL = False

if LOCAL:
    GOOGLE_REDIRECT = 'http://127.0.0.1:8000/oauth2/redirect/'
    STATIC_URL ='static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
else:
    GOOGLE_REDIRECT = 'http://10khours.ru/oauth2/redirect/'
    STATIC_URL = None
    STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'public_html')
    
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(os.path.dirname(BASE_DIR), 'public_html')
]

ALLOWED_HOSTS = ['10khours.ru']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    # 'djcelery',
    'gauth',
    'accounts',
    'viz',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hours.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                   'django.contrib.auth.context_processors.auth',
                   'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
   'django.contrib.auth.backends.ModelBackend',
)


WSGI_APPLICATION = 'hours.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
