# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('next_run', models.DateTimeField()),
                ('repeat', models.CharField(choices=[('every_day', 'Every Day'), ('every_week', 'every Week'), ('every_month', 'every Month')], max_length=20)),
                ('periods', models.CharField(choices=[('this_month', 'this month'), ('last_30_days', 'last 30 days'), ('this_week', 'this week')], max_length=20)),
            ],
        ),
    ]
