# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateField(),
        ),
    ]
