# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0002_auto_20161126_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('delta', models.DurationField()),
            ],
        ),
    ]
