# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0003_periodmanager_periodmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodmodel',
            name='calendar',
            field=models.ForeignKey(default='abroskingleb@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='viz.CalendarModel'),
            preserve_default=False,
        ),
    ]
