# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0004_periodmodel_calendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodManager',
        ),
    ]
