# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0006_auto_20161207_0109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarModel',
            new_name='Calendar',
        ),
    ]
