# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0007_auto_20161207_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='name',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='update_time',
            new_name='updated',
        ),
    ]
