# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0008_auto_20161207_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.FloatField(),
        ),
    ]
